### ISSUE TITLE
Feature request: Live win percentage on scoreboard route (/scoreboard/basketball-men/d1)

### ISSUE THREAD

**Issue by andrewheekin** [henrygd/ncaa-api#1]
Very cool project! Just curious, does the NCAA site have a live in-game win percentage or odds that you've seen?

**Comment by andrewheekin** [comment]
I found this endpoint from DraftKings, which may have this data https://sportsbook.draftkings.com/sites/US-SB/api/v4/featured/live?format=json

**Comment by henrygd** [comment]
Looks like the hidden ESPN endpoint has it if a game is live.

https://gist.github.com/akeaswaran/b48b02f1c94f873c6655e7129910fc3b

```
events[0].competitions[0].situation.lastPlay.probability
```

```js
{
    "tiePercentage": 0,
    "homeWinPercentage": 0.222,
    "awayWinPercentage": 0.778
}
```
