### ISSUE TITLE
Game Details

### ISSUE THREAD

**Issue by DreamingInBinary** [henrygd/ncaa-api#2]
Hey there - 

I was wondering if there were any plans to parse urls like this:

https://www.ncaa.com/game/6351241

Specifically, the box score. I assume this would be hard to do, since that data is likely stuff in an `<iframe>` or some other means, but figured I'd ask!

**Comment by henrygd** [comment]
Game routes have been added in 1.3.0.

Example game: https://www.ncaa.com/game/6305900

- `/game/6305900` or `/game/6305900/boxscore` returns box score
- `/game/6305900/play-by-play` returns play by play
- `/game/6305900/scoring-summary` returns scoring summary if available
- `/game/6305900/team-stats` returns team stats if available

Let me know if you have any trouble with it.

**Comment by DreamingInBinary** [comment]
Amazing!! I am planning on shipping an app using this, I have a beta here if you want to try it out: https://testflight.apple.com/join/jEAY4YBj

Will setup self hosting soon too so I don't put any extra load on your server.

**Comment by henrygd** [comment]
Nice! I don't have an Apple device, but I see the screenshots on your twitter and it looks great!

Keep in mind that the data is being pulled from the NCAA website, so the API could break if something changes on that end. However I doubt that will happen anytime soon.

The server is fairly lightweight and can handle a lot of traffic in a single instance. You can also put a CDN in front of it to serve cached data.

By default, the `/scoreboard` and `/game` routes are cached for 1 minute. Other routes are cached for 30 minutes.

Let me know if you have any questions.
